name: DevSecOps Secure Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: |
          pip install bandit==1.9.4

      - name: Run Bandit SAST scan
        run: |
          mkdir -p reports
          bandit -r app/ -f txt -o reports/bandit-report.txt || true

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: reports/bandit-report.txt

      - name: Build Docker image
        run: |
          docker build -t devsecops-app .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
            sudo sh -s -- -b /usr/local/bin v0.74.0

      - name: Run Trivy vulnerability scan
        run: |
          mkdir -p reports
          trivy image \
            --scanners vuln \
            --format json \
            -o reports/trivy-report.json \
            devsecops-app

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: reports/trivy-report.json

      - name: Enforce security policy
        run: |
          trivy image \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            devsecops-app
